### PR TITLE
Debian source format: 3.0 (quilt)

### PR DESCRIPTION
**Pull request by pini-gh**
Hi Radek,

I've finally managed to sync again your changes into my GitHub repo and here is the very first pull request from my set of changes. Its purpose is to configure qtmoko as a _non-native_ Debian package.

Please read http://wiki.debian.org/DebianMentorsFaq#What_is_the_difference_between_a_native_Debian_package_and_a_non-native_package.3F  for the rationals.

Would it be ok for you to use the following layout?
- master = development only; no packaging; no debian subdir
- translations = release; no packaging; no debian subdir
- debian = release ; packaging ; debian subdir

Or maybe simpler, since I've found out that building with translations doesn't take more time than without them :
- master = development with translations ; no packaging ; no debian subdir
- debian = release ; packaging ; debian subdir

These ways the package build proccess conforms to Debian standards and can be handled using pdebuild-cross, into a clean squeeze chroot (best to check for missing Build-Depends).

Many thanks in advance.

_g.

### CODE REVIEW

**Comment by pini-gh** [comment]
Oh well... I guess I'll have to learn again how pull requests work. I wanted debian/source/format only into this one, but it seems that two commits from my last push have entered in as well.

One deals with a typo into debian/qtmoko-gta04.install which should have 'gta04' instead of 'neo' in its content.

The other adds missing Build-Depends to debian/control.

Thanks,

_g.

**Comment by radekp** [comment]
I have cherry-picked the last two commits, so it should be ok now.

As for the layout - i'd like to keep debian subdir versioned - it's very important
to see the changes.

And adding another branch means more maintanance work. You have to merge
the branches together and very often you accidentaly commit in the wrong branch.
It took many days to get rid of master_gta04 and translations_gta04 i am not sure
if i am yet ready to add another branch ;-)

Are there any other possibilities to solve the problem? Maybe we could move the
debian dir to packagin/debian so that it would conform debian requirements?

**Comment by pini-gh** [comment]
Hi Radek,

----- Mail original -----

> De: "Radek Polak" notifications@github.com
> À: "radekp/qtmoko" qtmoko@noreply.github.com
> Cc: "pini-gh" gilles.filippini@free.fr
> Envoyé: Vendredi 21 Septembre 2012 08:55:52
> Objet: Re: [qtmoko] Debian source format: 3.0 (quilt) (#132)
> 
> As for the layout - i'd like to keep debian subdir versioned - it's
> very important
> to see the changes.

Indeed, I agree.

> And adding another branch means more maintanance work. You have to
> merge
> the branches together and very often you accidentaly commit in the
> wrong branch.
> It took many days to get rid of master_gta04 and translations_gta04 i
> am not sure
> if i am yet ready to add another branch ;-)

Is there actually a significant overhead integrating translations to the main developement branch (master)? This way you'd have only to branches:
- master (development + translations)
- debian (master + debian subdir)

> Are there any other possibilities to solve the problem? Maybe we
> could move the
> debian dir to packagin/debian so that it would conform debian
> requirements?

No. The point is to have a git branch from which git-buildpackage can generate the qtmoko_<version>.orig.tar.gz source tarball (without the debian subdir).

Anyway, I think I can live with the current state of things. But maybe one day we'll have to thing about pushing QtMoko into Debian :) For now I have a local "upstream" forked from "translations" minus the debian subdir.

Thanks,

_g.

**Comment by pini-gh** [comment]
Hi,

Here is another bunch of commits (acc02a3 to da3491a) which purposes are:
- to have debian/rules clean properly revert the source tree changes occurred during the build
- to be able to build for only one device, using the QTMOKO_DEVICES environment variable. For example:
  
  $ QTMOKO_DEVICES=gta04 pdebuild-cross

Thanks,

_g.

**Comment by radekp** [comment]
Hi, after this commits i am getting:

dpkg-source: error: can't build with source format '3.0 (quilt)': no orig.tar file found
dpkg-buildpackage: error: dpkg-source -b qtmoko gave error exit status 255

Any idea what is wrong? I am just doing dpkg-buildpackage in qtmoko source dir. It
used to work fine with native format.

**Comment by pini-gh** [comment]
> De: "Radek Polak" notifications@github.com
> À: "radekp/qtmoko" qtmoko@noreply.github.com
> Cc: "pini-gh" gilles.filippini@free.fr
> Envoyé: Jeudi 27 Septembre 2012 11:19:39
> Objet: Re: [qtmoko] Debian source format: 3.0 (quilt) (#132)
> 
> Hi, after this commits i am getting:
> 
> dpkg-source: error: can't build with source format '3.0 (quilt)': no
> orig.tar file found
> dpkg-buildpackage: error: dpkg-source -b qtmoko gave error exit
> status 255
> 
> Any idea what is wrong? I am just doing dpkg-buildpackage in qtmoko
> source dir. It
> used to work fine with native format.

Indeed. You need to first generate the orig.tar.gz source file. This is
the purpose of the debian/rules get-orig-source target.

Please try before-hand:
$ debian/rules get-orig-source

And go back to me in case it goes wrong :)

Thanks,

_g.

**Comment by radekp** [comment]
On Thursday, September 27, 2012 02:24:46 PM pini-gh wrote:

> Indeed. You need to first generate the orig.tar.gz source file. This is
> the purpose of the debian/rules get-orig-source target.
> 
> Please try before-hand:
> $ debian/rules get-orig-source
> 
> And go back to me in case it goes wrong :)

It's building now, thanks! Btw have you tried building the package with git-
buildpackage?

**Comment by pini-gh** [comment]
Radek Polak a écrit , Le 01/10/2012 13:50:

> It's building now, thanks! Btw have you tried building the package with git-
> buildpackage?

No I haven't. I use it for native building of my other packages, but I
don't think it supports cross-building.
I use pdebuild-cross instead (see my two last commits).

Thanks,

_g.

**Pull request merged**
