### PR TITLE
pdebuild-cross config enhancements + minor fixes

### PR DESCRIPTION
**Pull request by pini-gh**
Hi Radek,

Time for a pull request again :)

The main changes are in my pdebuild-cross configuration files which support now multiple configurations depending on arch, dist, and gcc version.

The remaining is debian/rules cleaning.

Also, I've tried building against your Qt v4.8.3-qtmoko-v49 branch, with no success so far. Could you please push your related qtmoko commits?

Thanks in advance,

_g.

### CODE REVIEW

**Comment by radekp** [comment]
Thanks for the patches! I dont have any other commits for v4.8.3-qtmoko-v49 branch yet. For me it already compiles and works - but still it has some bugs (e.g. after installing new app the icon is not shown up).

I only had to install some more dependencies - IIRC gst-plugins or something like this is now needed by webkit. I am now trying to figure out if we want/need gstreamer (probably used for html5 videos - but they dont work for me yet anyways).

My cross-compile configure command line is now:

../qtmoko/configure -device gta04 -system-qt -I /usr/arm-linux-gnueabi/include/glib-2.0 -I /usr/arm-linux-gnueabi/lib/glib-2.0/include/ -I /usr/arm-linux-gnueabi/include/gstreamer-0.10 -I /usr/arm-linux-gnueabi/include/libxml2

**Comment by pini-gh** [comment]
Radek Polak a écrit , Le 08/10/2012 06:38:

> Thanks for the patches! I dont have any other commits for
> v4.8.3-qtmoko-v49 branch yet. For me it already compiles and works - but

That's strange. For example I've had to change the links for the broken
lib names in debian/rules:
- added the Source directory into the path
- added a link for libwebcore.a

I then had a linker error with undefined reference to QObject, which I
don't know do to deal with.

> still it has some bugs (e.g. after installing new app the icon is not
> shown up).
> 
> I only had to install some more dependencies - IIRC gst-plugins or
> something like this is now needed by webkit. I am now trying to figure
> out if we want/need gstreamer (probably used for html5 videos - but they
> dont work for me yet anyways).
> 
> My cross-compile configure command line is now:
> 
> ../qtmoko/configure -device gta04 -system-qt -I
> /usr/arm-linux-gnueabi/include/glib-2.0 -I
> /usr/arm-linux-gnueabi/lib/glib-2.0/include/ -I
> /usr/arm-linux-gnueabi/include/gstreamer-0.10 -I
> /usr/arm-linux-gnueabi/include/libxml2

Will try this. Thanks,

_g

**Comment by radekp** [comment]
On Monday, October 08, 2012 09:14:15 AM pini-gh wrote:

> Radek Polak a écrit , Le 08/10/2012 06:38:
> 
> > Thanks for the patches! I dont have any other commits for
> > v4.8.3-qtmoko-v49 branch yet. For me it already compiles and works - but
> 
> That's strange. For example I've had to change the links for the broken
> lib names in debian/rules:
> - added the Source directory into the path
> - added a link for libwebcore.a

Ahh probably i replaced 4.7.4 with 4.8.2 in debian/rules

> I then had a linker error with undefined reference to QObject, which I
> don't know do to deal with.

No idea here too - i haven tried cross compiling yet. Maybe it's again because 
different compiler flags.

**Comment by pini-gh** [comment]
Radek Polak a écrit , Le 08/10/2012 10:11:

> On Monday, October 08, 2012 09:14:15 AM pini-gh wrote:
> 
> > I then had a linker error with undefined reference to QObject, which I
> > don't know do to deal with.
> 
> No idea here too - i haven tried cross compiling yet. Maybe it's again
> because
> different compiler flags.

Here is the error, occurring at link step for tst_qwebframe in:
build-gta04/qtopiacore/target/src/3rdparty/webkit/Source/WebKit/qt/tests/qwebframe

arm-linux-gnueabihf-g++
-Wl,-rpath-link,/tmp/buildd/build-gta04/qtopiacore/target/lib
-Wl,-z,relro
-Wl,-rpath-link,/tmp/buildd/qtmoko-49~pini4/qtopiacore/qt/src/3rdparty/webkit/Source/lib
-Wl,-rpath-link,/tmp/buildd/build-gta04/sdk/qtopiacore/target/lib
-Wl,-rpath-link,/tmp/buildd/build-gta04/sdk/qtopiacore/target/lib
-Wl,-rpath-link,/tmp/buildd/build-gta04/sdk/lib -o tst_qwebframe
.obj/release-shared-emb-arm/tst_qwebframe.o
.obj/release-shared-emb-arm/qrc_tst_qwebframe.o
-L/tmp/buildd/build-gta04/qtopiacore/target/lib
-L/usr/arm-linux-gnueabihf/lib
-L/tmp/buildd/build-gta04/qtopiacore/target/lib
-L/usr/arm-linux-gnueabihf/lib -lQtDeclarative -lQtWebKit -lQtTest -ldl
-ldbus-1 -lQtGui -lQtNetwork -lQtCore -lpthread
/usr/arm-linux-gnueabihf/lib/libQtTest.so: undefined reference to
`typeinfo for QObject'

The WWW tells me [1] that this occurs when declared (non-pure) virtual
functions are missing bodies or should be declared pure virtual (=0).

[1] http://stackoverflow.com/a/307381

IMHO this kind of error isn't related to cross-compiling, but maybe to
compiler version. Which one do you build with? Mine is 4.6.

Thanks,

_g.

**Comment by radekp** [comment]
On Tuesday, October 09, 2012 12:24:36 AM pini-gh wrote:

> arm-linux-gnueabihf-g++
> -Wl,-rpath-link,/tmp/buildd/build-gta04/qtopiacore/target/lib
> -Wl,-z,relro
> -Wl,-rpath-link,/tmp/buildd/qtmoko-49~pini4/qtopiacore/qt/src/3rdparty/webk
> it/Source/lib
> -Wl,-rpath-link,/tmp/buildd/build-gta04/sdk/qtopiacore/target/lib
> -Wl,-rpath-link,/tmp/buildd/build-gta04/sdk/qtopiacore/target/lib
> -Wl,-rpath-link,/tmp/buildd/build-gta04/sdk/lib -o tst_qwebframe
> .obj/release-shared-emb-arm/tst_qwebframe.o
> .obj/release-shared-emb-arm/qrc_tst_qwebframe.o
> -L/tmp/buildd/build-gta04/qtopiacore/target/lib
> -L/usr/arm-linux-gnueabihf/lib
> -L/tmp/buildd/build-gta04/qtopiacore/target/lib
> -L/usr/arm-linux-gnueabihf/lib -lQtDeclarative -lQtWebKit -lQtTest -ldl
> -ldbus-1 -lQtGui -lQtNetwork -lQtCore -lpthread
> /usr/arm-linux-gnueabihf/lib/libQtTest.so: undefined reference to
> `typeinfo for QObject'
> 
> The WWW tells me [1] that this occurs when declared (non-pure) virtual
> functions are missing bodies or should be declared pure virtual (=0).
> 
> [1] http://stackoverflow.com/a/307381
> 
> IMHO this kind of error isn't related to cross-compiling, but maybe to
> compiler version. Which one do you build with? Mine is 4.6.
> 
> Thanks,

Mine is slightly older (using cross compiler from emdebian):

/usr/bin/arm-linux-gnueabi-gcc --version
arm-linux-gnueabi-gcc (Debian 4.4.5-8) 4.4.5

**Pull request merged**
