### PR TITLE
Improving the Debian source package (Part two)

### PR DESCRIPTION
**Pull request by pini-gh**
Hi Radek,

Here is a second bunch of commits related to the qtmoko Debian source package. The commit messages should be self-explanatory. But one never knows :) Please ask your questions if any !

Thanks,

_g.

### CODE REVIEW

**Comment by radekp** [comment]
On Tuesday 13 December 2011 21:07:46 you wrote:

> Hi Radek,
> 
> Here is a second bunch of commits related to the qtmoko Debian source
> package. The commit messages should be self-explanatory. But one never
> knows :) Please ask your questions if any !
> 
> https://github.com/radekp/qtmoko/pull/2

Hi,
it looks great. I have pulled it (but not tested yet ;-)

Thanks!

Radek

**Comment by pini-gh** [comment]
Radek Polak a écrit , Le 13/12/2011 23:43:

> On Tuesday 13 December 2011 21:07:46 you wrote:
> it looks great. I have pulled it (but not tested yet ;-)

I've juste pushed a last fix (260d6a6d00): the binary package was
missing the init script.

Thanks,

_g.

**Comment by radekp** [comment]
On Tuesday 13 December 2011 22:54:21 you wrote:

> I've juste pushed a last fix (260d6a6d00): the binary package was
> missing the init script.

Pulled it too, thanks!

Radek

**Comment by pini-gh** [comment]
Radek,

Still another push related to the qtmoko init script. Hopefully the last
one for this topic.

I've reverted the script's name to qtmoko instead of
qtmoko-$(QTMOKO_DEVICE) so that no extra script remains into
/etc/init.d/ after an upgrade from qtmoko to qtmoko-$(QTMOKO_DEVICE).

Thanks,

_g.

**Pull request merged**
