### PR TITLE
Improving the Debian source package

### PR DESCRIPTION
**Pull request by pini-gh**
Hi Radek,

I've spent some time trying to improve the qtmoko Debian source package so that it could build with pdebuild-cross and the emdebian toolchain. Here is the result.

Please consider including these changes into your repo.

Many thanks in advance,

_g.

### CODE REVIEW

**Comment by radekp** [comment]
On Friday 09 of December 2011 21:35:49 you wrote:

> Hi Radek,
> 
> I've spent some time trying to improve the qtmoko Debian source package so
> that it could build with pdebuild-cross and the emdebian toolchain. Here is
> the result.
> 
> Please consider including these changes into your repo.

Hi, this is great. Sorry for late reply, i didnt have access to computer in 
last 2 days. I'll take a look now.

Regards

Radek

**Comment by radekp** [comment]
I have pulled it now. Btw what is purpose of the patches in debian/patches? Maybe it would be better to apply them straight to source code?

**Comment by pini-gh** [comment]
Radek Polak a écrit , Le 11/12/2011 10:26:

> I have pulled it now.

Great!

> Btw what is purpose of the patches in debian/patches? Maybe it would be better to apply them straight to source code?

Sure. It's a Debian maintainer common practice to proceed with patches
:) But once accepted upstream it's better to have them applied on the
source tree.

Thanks,

_g.

**Comment by radekp** [comment]
One more question :) Do the patches fix compiler warnings or some other problem?

**Comment by pini-gh** [comment]
Radek Polak a écrit , Le 11/12/2011 16:52:

> One more question :) Do the patches fix compiler warnings or some other problem?

The patch fixes compiler _errors_ "format not a string literal and no
format arguments" encountered with g++-4.4.

The fixes are all of this kind:

replace q{Warning|Fatal|Critical}(QString())
with q{Warning|Fatal|Critical}("%s", QString())

_g.

**Comment by radekp** [comment]
Oki, could you please apply them to master so that i can pull it?

**Comment by pini-gh** [comment]
Radek Polak a écrit , Le 11/12/2011 17:58:

> Oki, could you please apply them to master so that i can pull it?

Done, along with two other self-describing commits:

commit 7f0183f8ed14a1682ebc180d807f6e9d80742833
Author: Gilles Filippini pini@debian.org
Date:   Sun Dec 11 18:38:32 2011 +0100

```
Applied patch format-not-a-string-literal-and-no-format-arguments.patch
to upstream source tree
```

commit 64a7ecfb7ef31adb6b8597cfbd0d50c8571712f2
Author: Gilles Filippini pini@debian.org
Date:   Sun Dec 11 18:37:49 2011 +0100

```
New file debian/README.source

to explain how to cross build the package using the emdebian toolchain.
```

commit cdb48b3edb82f9eae4a1ed64717300a707d54e02
Author: Gilles Filippini pini@debian.org
Date:   Sun Dec 11 18:19:55 2011 +0100

```
Fix typo: s/QT_MOKO_DEVICE/QTMOKO_DEVICE/g
```

Should I initiate a new pull request? Anyway expect a few ones in the
next days as I go forward cleaning up the source package :)

_g.

**Comment by radekp** [comment]
Hi, i pulled it now, looking forward next patches

**Pull request merged**
